"""add receipt confirmations

Revision ID: 05c83b088c12
Revises: aaecc3682451
Create Date: 2026-07-22 16:16:13.669120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c83b088c12'
down_revision: Union[str, Sequence[str], None] = 'aaecc3682451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_samples',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_prediction_id', sa.Uuid(), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('target_payload', sa.JSON(), nullable=False),
    sa.Column('is_sanitized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_prediction_id'], ['receipt_predictions.id'], name='fk_training_samples_source_prediction', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_prediction_id', name='uq_training_samples_source_prediction')
    )
    op.create_index(op.f('ix_training_samples_user_id'), 'training_samples', ['user_id'], unique=False)
    op.add_column('receipt_predictions', sa.Column('confirmed_receipt_id', sa.Uuid(), nullable=True))
    op.add_column('receipt_predictions', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_receipt_predictions_confirmed_receipt', 'receipt_predictions', ['confirmed_receipt_id'])
    op.create_foreign_key('fk_receipt_predictions_confirmed_receipt', 'receipt_predictions', 'receipts', ['confirmed_receipt_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_receipt_predictions_confirmed_receipt', 'receipt_predictions', type_='foreignkey')
    op.drop_constraint('uq_receipt_predictions_confirmed_receipt', 'receipt_predictions', type_='unique')
    op.drop_column('receipt_predictions', 'confirmed_at')
    op.drop_column('receipt_predictions', 'confirmed_receipt_id')
    op.drop_index(op.f('ix_training_samples_user_id'), table_name='training_samples')
    op.drop_table('training_samples')
    # ### end Alembic commands ###
