"""initial schema

Revision ID: 71469e30587c
Revises: 
Create Date: 2026-07-22 08:54:12.664330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71469e30587c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('receipt_draft_id', sa.Uuid(), nullable=False),
    sa.Column('image_ref', sa.String(length=1000), nullable=False),
    sa.Column('extractor_name', sa.String(length=255), nullable=False),
    sa.Column('model_output', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'receipt_draft_id', name='uq_receipt_predictions_user_draft')
    )
    op.create_index(op.f('ix_receipt_predictions_receipt_draft_id'), 'receipt_predictions', ['receipt_draft_id'], unique=False)
    op.create_index(op.f('ix_receipt_predictions_user_id'), 'receipt_predictions', ['user_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_currency', sa.String(length=3), nullable=False),
    sa.Column('image_ref', sa.String(length=1000), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_user_id'), 'receipts', ['user_id'], unique=False)
    op.create_table('receipt_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('total_price_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price_currency', sa.String(length=3), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('bucket', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit_price_currency', sa.String(length=3), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_items_receipt_id'), 'receipt_items', ['receipt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_items_receipt_id'), table_name='receipt_items')
    op.drop_table('receipt_items')
    op.drop_index(op.f('ix_receipts_user_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_receipt_predictions_user_id'), table_name='receipt_predictions')
    op.drop_index(op.f('ix_receipt_predictions_receipt_draft_id'), table_name='receipt_predictions')
    op.drop_table('receipt_predictions')
    # ### end Alembic commands ###
