"""add receipt financial fields

Revision ID: aaecc3682451
Revises: 71469e30587c
Create Date: 2026-07-22 09:10:53.110709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaecc3682451'
down_revision: Union[str, Sequence[str], None] = '71469e30587c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('subtotal_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('receipts', sa.Column('subtotal_currency', sa.String(length=3), nullable=True))
    op.add_column('receipts', sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('receipts', sa.Column('tax_currency', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'tax_currency')
    op.drop_column('receipts', 'tax_amount')
    op.drop_column('receipts', 'subtotal_currency')
    op.drop_column('receipts', 'subtotal_amount')
    # ### end Alembic commands ###
